application: nodal-ivy-88401
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloudacity.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest